spring:
  application:
    name: report-service

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      enable-auto-commit: true
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
          kafka:
            consumer:
              max:
                poll:
                  records: 10
                  interval:
                    ms: 300000
logging:
  level:
    org:
      springframework:
        boot: INFO


server:
  port: 8083